### ISSUE TITLE
Čísla a názvy týmů

### ISSUE THREAD

**Issue by SuperMartas** [FitIW/5#6]
V zadání projektu se používají čísla týmů, ale ve wisu mi není zcela jasné, co je číslem týmu myšleno, resp. zda je jeho použití korektní. Ve wisu vidíme následující:
![Týmy ve wisu](https://user-images.githubusercontent.com/7558984/52496297-42c7e080-2bd3-11e9-98a5-ea6295d03b96.png)

Jedná se tedy o sloupec # nebo o ID v adrese (team=0000)?

Pokud by se jednalo o sloupec #, tak ten není bohužel neměnný a vyjadřuje pouze pořadí v tabulce. Když tak např. použiji nějaký filtr (jako je např. "select vše/můj" zobrazený na obrázku) nebo někdo vytvoří nový tým, tak se čísla týmů změní.

Pokud by se jednalo o ID v odkazu, tak pak by se v případě, že někdo má zaregistrované předměty ICS i IW5, muselo ještě navíc specifikovat ID kterého týmu se použije (jestli toho založeného v ICS nebo v IW5 - jedná se totiž o rozdílné týmy). V tomto případě si ale nejsem jistý, zda byla tato možnost myšlena, protože se jedná většinou o čísla o 4 číslicích, ale v zadání jsou předvyplněny jenom 2 číslice.

Mimo to mi není jasné, jak se budou vytvářet názvy týmů v letošním roce. Aktualita v README na master větvi totiž naznačuje, že názvy se budou vytvářet podle schématu "iw5-2019-team00", resp. "ics-iw5-2019-team00". V zadání projektu pro letošní rok (ve větvi "projekt") je ovšem pouze varianta "iw5-2019-team<00>" a dokonce je tam i rozpor v názvu projektu (je po nás vyžadován název projektu "projekt", ale v ukázkovém odkazu je název projektu "project").

Jak to tedy je pro letošní rok správně?

**Comment by pluskal** [comment]
Díky za Vaši aktivitu! 

Sám jsem si nebyl zcela jistý tím, co vidíte v studentském WISu.  Po konzultaci s Ing. Lampou jsem zvolil variantu ID z URL. Opravil jsem tedy schéma v *master* větvi a README.md by již mělo být v pořádku. 

Větev *projekt* je stále ve vývoji a jakmile doladíme zadání, provedu merge do *master*.

**Comment by SuperMartas** [comment]
Děkuji za odpověď. Jen to ještě neřeší případ v mém původním příspěvku, kdy tým řeší variantu IW5/ICS (studenti mají zaregistrovaný jak předmět ICS, tak i IW5). ID kterého týmu se má zvolit? Toho z ICS nebo IW5? Jedná se totiž jakoby o dva naprosto odlišné týmy (= mají jiná ID).

**Comment by pluskal** [comment]
To už pro mne není tak podstatné, ale ať to máme jednotné, tak použijte prosím ICS.

**Comment by SuperMartas** [comment]
Děkuji za objasnění. V případě, že to uznáte za vhodné, můžete tento issue uzavřít (close issue).
